export const articleTags = [
  { value: "software-engineering", label: "Software Engineering" },
  { value: "programming-languages", label: "Programming Languages" },
  { value: "web-development", label: "Web Development" },
  { value: "machine-learning", label: "Machine Learning" },
  { value: "devops", label: "DevOps" },
  { value: "data-structures", label: "Data Structures" },
  { value: "algorithms", label: "Algorithms" },
  { value: "system-design", label: "System Design" },
  { value: "testing", label: "Testing & QA" },
  { value: "cloud-computing", label: "Cloud Computing" },
  { value: "software-testing", label: "Software Testing" },
  { value: "api-development", label: "API Development" },
  { value: "version-control", label: "Version Control" },
  { value: "ci-cd", label: "CI/CD Pipelines" },
  { value: "design-patterns", label: "Design Patterns" },
];

export const technologiesOptions = [
  { value: "javascript", label: "JavaScript" },
  { value: "typescript", label: "TypeScript" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "csharp", label: "C#" },
  { value: "php", label: "PHP" },
  { value: "ruby", label: "Ruby" },
  { value: "go", label: "Go" },
  { value: "rust", label: "Rust" },
  { value: "nodejs", label: "Node.js" },
  { value: "react", label: "React" },
  { value: "vue", label: "Vue.js" },
  { value: "angular", label: "Angular" },
  { value: "nextjs", label: "Next.js" },
  { value: "nuxtjs", label: "Nuxt.js" },
  { value: "django", label: "Django" },
  { value: "flask", label: "Flask" },
  { value: "springboot", label: "Spring Boot" },
  { value: "express", label: "Express" },
  { value: "mongodb", label: "MongoDB" },
  { value: "mysql", label: "MySQL" },
  { value: "postgresql", label: "PostgreSQL" },
  { value: "firebase", label: "Firebase" },
  { value: "aws", label: "AWS" },
  { value: "azure", label: "Azure" },
  { value: "gcp", label: "Google Cloud" },
  { value: "docker", label: "Docker" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "tailwind", label: "Tailwind CSS" },
  { value: "sass", label: "Sass" },
];
